// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/hoangcn95/go-coffeeshop-imitate/workings/cmd/product/config"
	"github.com/hoangcn95/go-coffeeshop-imitate/workings/internal/product/app/router"
	"github.com/hoangcn95/go-coffeeshop-imitate/workings/internal/product/infras/inmem"
	"github.com/hoangcn95/go-coffeeshop-imitate/workings/internal/product/service/products"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, grpcServer *grpc.Server) (*App, error) {
	productRepo := inmem.NewOrderRepo()
	productService := products.NewProductService(productRepo)
	productServiceServer := router.NewProductGRPCServer(grpcServer, productService)
	app := New(cfg, productService, productServiceServer)
	return app, nil
}
